"""Add created_at and content_type fields

Revision ID: 3b97337f8e79
Revises: 0872e1999baa
Create Date: 2026-03-08 17:47:12.823971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b97337f8e79"
down_revision: Union[str, Sequence[str], None] = "0872e1999baa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("content_type", sa.VARCHAR(), nullable=True))
    op.add_column("document", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("project", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "created_at")
    op.drop_column("document", "created_at")
    op.drop_column("document", "content_type")
    # ### end Alembic commands ###
